Parameters:
  Prefix:
    Type: String
    Description: "Prefix for naming resources"
    Default: "my"  # You can set a default value or leave it empty for users to specify

  MySecretToken:
    Type: String
    Description: "The secret token to be stored in Parameter Store"
    NoEcho: true  # This prevents the token from being displayed in plaintext

Resources:
  MyTokenParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Prefix}/myapp/token"  # Customize this path if needed
      Type: "String"  # Change to "SecureString" if secure storage is required and your CloudFormation supports it
      Value: !Ref MySecretToken
      Description: "Token used for authentication in my application"
